//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CartaGuia {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet2 : DataSet {
        
        private _TableDataTable table_Table;
        
        public DataSet2() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet2(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Table"] != null)) {
                    this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public _TableDataTable _Table {
            get {
                return this.table_Table;
            }
        }
        
        public override DataSet Clone() {
            DataSet2 cln = ((DataSet2)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Table"] != null)) {
                this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.table_Table = ((_TableDataTable)(this.Tables["Table"]));
            if ((this.table_Table != null)) {
                this.table_Table.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet2";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet2.xsd";
            this.Locale = new System.Globalization.CultureInfo("es-CL");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.table_Table = new _TableDataTable();
            this.Tables.Add(this.table_Table);
        }
        
        private bool ShouldSerialize_Table() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void _TableRowChangeEventHandler(object sender, _TableRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnENVI_NCORR;
            
            private DataColumn columnENVI_FENVIO;
            
            private DataColumn columnINEN_CCOD;
            
            private DataColumn columnINEN_TDESC;
            
            private DataColumn columnPLAZ_CCOD;
            
            private DataColumn columnPLAZ_TDESC;
            
            private DataColumn columnRUT_ALUMNO;
            
            private DataColumn columnNOMBRE_APODERADO;
            
            private DataColumn columnRUT_APODERADO;
            
            private DataColumn columnDIRECCION;
            
            private DataColumn columnDING_FDOCTO;
            
            private DataColumn columnDING_MDETALLE;
            
            private DataColumn columnDING_NDOCTO;
            
            private DataColumn columnINGR_NCORR;
            
            private DataColumn columnTING_CCOD;
            
            private DataColumn columnCCTE_TDESC;
            
            private DataColumn columnSEDE_TCALLE;
            
            private DataColumn columnSEDE_TNRO;
            
            private DataColumn columnCCTE_CCOD;
            
            private DataColumn columnSEDE_CCOD;
            
            private DataColumn columnESPE_TDESC;
            
            private DataColumn columnEDIN_TDESC;
            
            private DataColumn columnINGR_FPAGO;
            
            internal _TableDataTable() : 
                    base("Table") {
                this.InitClass();
            }
            
            internal _TableDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ENVI_NCORRColumn {
                get {
                    return this.columnENVI_NCORR;
                }
            }
            
            internal DataColumn ENVI_FENVIOColumn {
                get {
                    return this.columnENVI_FENVIO;
                }
            }
            
            internal DataColumn INEN_CCODColumn {
                get {
                    return this.columnINEN_CCOD;
                }
            }
            
            internal DataColumn INEN_TDESCColumn {
                get {
                    return this.columnINEN_TDESC;
                }
            }
            
            internal DataColumn PLAZ_CCODColumn {
                get {
                    return this.columnPLAZ_CCOD;
                }
            }
            
            internal DataColumn PLAZ_TDESCColumn {
                get {
                    return this.columnPLAZ_TDESC;
                }
            }
            
            internal DataColumn RUT_ALUMNOColumn {
                get {
                    return this.columnRUT_ALUMNO;
                }
            }
            
            internal DataColumn NOMBRE_APODERADOColumn {
                get {
                    return this.columnNOMBRE_APODERADO;
                }
            }
            
            internal DataColumn RUT_APODERADOColumn {
                get {
                    return this.columnRUT_APODERADO;
                }
            }
            
            internal DataColumn DIRECCIONColumn {
                get {
                    return this.columnDIRECCION;
                }
            }
            
            internal DataColumn DING_FDOCTOColumn {
                get {
                    return this.columnDING_FDOCTO;
                }
            }
            
            internal DataColumn DING_MDETALLEColumn {
                get {
                    return this.columnDING_MDETALLE;
                }
            }
            
            internal DataColumn DING_NDOCTOColumn {
                get {
                    return this.columnDING_NDOCTO;
                }
            }
            
            internal DataColumn INGR_NCORRColumn {
                get {
                    return this.columnINGR_NCORR;
                }
            }
            
            internal DataColumn TING_CCODColumn {
                get {
                    return this.columnTING_CCOD;
                }
            }
            
            internal DataColumn CCTE_TDESCColumn {
                get {
                    return this.columnCCTE_TDESC;
                }
            }
            
            internal DataColumn SEDE_TCALLEColumn {
                get {
                    return this.columnSEDE_TCALLE;
                }
            }
            
            internal DataColumn SEDE_TNROColumn {
                get {
                    return this.columnSEDE_TNRO;
                }
            }
            
            internal DataColumn CCTE_CCODColumn {
                get {
                    return this.columnCCTE_CCOD;
                }
            }
            
            internal DataColumn SEDE_CCODColumn {
                get {
                    return this.columnSEDE_CCOD;
                }
            }
            
            internal DataColumn ESPE_TDESCColumn {
                get {
                    return this.columnESPE_TDESC;
                }
            }
            
            internal DataColumn EDIN_TDESCColumn {
                get {
                    return this.columnEDIN_TDESC;
                }
            }
            
            internal DataColumn INGR_FPAGOColumn {
                get {
                    return this.columnINGR_FPAGO;
                }
            }
            
            public _TableRow this[int index] {
                get {
                    return ((_TableRow)(this.Rows[index]));
                }
            }
            
            public event _TableRowChangeEventHandler _TableRowChanged;
            
            public event _TableRowChangeEventHandler _TableRowChanging;
            
            public event _TableRowChangeEventHandler _TableRowDeleted;
            
            public event _TableRowChangeEventHandler _TableRowDeleting;
            
            public void Add_TableRow(_TableRow row) {
                this.Rows.Add(row);
            }
            
            public _TableRow Add_TableRow(
                        string ENVI_NCORR, 
                        string ENVI_FENVIO, 
                        string INEN_CCOD, 
                        string INEN_TDESC, 
                        string PLAZ_CCOD, 
                        string PLAZ_TDESC, 
                        string RUT_ALUMNO, 
                        string NOMBRE_APODERADO, 
                        string RUT_APODERADO, 
                        string DIRECCION, 
                        string DING_FDOCTO, 
                        string DING_MDETALLE, 
                        string DING_NDOCTO, 
                        string INGR_NCORR, 
                        string TING_CCOD, 
                        string CCTE_TDESC, 
                        string SEDE_TCALLE, 
                        string SEDE_TNRO, 
                        string CCTE_CCOD, 
                        string SEDE_CCOD, 
                        string ESPE_TDESC, 
                        string EDIN_TDESC, 
                        string INGR_FPAGO) {
                _TableRow row_TableRow = ((_TableRow)(this.NewRow()));
                row_TableRow.ItemArray = new object[] {
                        ENVI_NCORR,
                        ENVI_FENVIO,
                        INEN_CCOD,
                        INEN_TDESC,
                        PLAZ_CCOD,
                        PLAZ_TDESC,
                        RUT_ALUMNO,
                        NOMBRE_APODERADO,
                        RUT_APODERADO,
                        DIRECCION,
                        DING_FDOCTO,
                        DING_MDETALLE,
                        DING_NDOCTO,
                        INGR_NCORR,
                        TING_CCOD,
                        CCTE_TDESC,
                        SEDE_TCALLE,
                        SEDE_TNRO,
                        CCTE_CCOD,
                        SEDE_CCOD,
                        ESPE_TDESC,
                        EDIN_TDESC,
                        INGR_FPAGO};
                this.Rows.Add(row_TableRow);
                return row_TableRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                _TableDataTable cln = ((_TableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new _TableDataTable();
            }
            
            internal void InitVars() {
                this.columnENVI_NCORR = this.Columns["ENVI_NCORR"];
                this.columnENVI_FENVIO = this.Columns["ENVI_FENVIO"];
                this.columnINEN_CCOD = this.Columns["INEN_CCOD"];
                this.columnINEN_TDESC = this.Columns["INEN_TDESC"];
                this.columnPLAZ_CCOD = this.Columns["PLAZ_CCOD"];
                this.columnPLAZ_TDESC = this.Columns["PLAZ_TDESC"];
                this.columnRUT_ALUMNO = this.Columns["RUT_ALUMNO"];
                this.columnNOMBRE_APODERADO = this.Columns["NOMBRE_APODERADO"];
                this.columnRUT_APODERADO = this.Columns["RUT_APODERADO"];
                this.columnDIRECCION = this.Columns["DIRECCION"];
                this.columnDING_FDOCTO = this.Columns["DING_FDOCTO"];
                this.columnDING_MDETALLE = this.Columns["DING_MDETALLE"];
                this.columnDING_NDOCTO = this.Columns["DING_NDOCTO"];
                this.columnINGR_NCORR = this.Columns["INGR_NCORR"];
                this.columnTING_CCOD = this.Columns["TING_CCOD"];
                this.columnCCTE_TDESC = this.Columns["CCTE_TDESC"];
                this.columnSEDE_TCALLE = this.Columns["SEDE_TCALLE"];
                this.columnSEDE_TNRO = this.Columns["SEDE_TNRO"];
                this.columnCCTE_CCOD = this.Columns["CCTE_CCOD"];
                this.columnSEDE_CCOD = this.Columns["SEDE_CCOD"];
                this.columnESPE_TDESC = this.Columns["ESPE_TDESC"];
                this.columnEDIN_TDESC = this.Columns["EDIN_TDESC"];
                this.columnINGR_FPAGO = this.Columns["INGR_FPAGO"];
            }
            
            private void InitClass() {
                this.columnENVI_NCORR = new DataColumn("ENVI_NCORR", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnENVI_NCORR);
                this.columnENVI_FENVIO = new DataColumn("ENVI_FENVIO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnENVI_FENVIO);
                this.columnINEN_CCOD = new DataColumn("INEN_CCOD", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINEN_CCOD);
                this.columnINEN_TDESC = new DataColumn("INEN_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINEN_TDESC);
                this.columnPLAZ_CCOD = new DataColumn("PLAZ_CCOD", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPLAZ_CCOD);
                this.columnPLAZ_TDESC = new DataColumn("PLAZ_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPLAZ_TDESC);
                this.columnRUT_ALUMNO = new DataColumn("RUT_ALUMNO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRUT_ALUMNO);
                this.columnNOMBRE_APODERADO = new DataColumn("NOMBRE_APODERADO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNOMBRE_APODERADO);
                this.columnRUT_APODERADO = new DataColumn("RUT_APODERADO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRUT_APODERADO);
                this.columnDIRECCION = new DataColumn("DIRECCION", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDIRECCION);
                this.columnDING_FDOCTO = new DataColumn("DING_FDOCTO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDING_FDOCTO);
                this.columnDING_MDETALLE = new DataColumn("DING_MDETALLE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDING_MDETALLE);
                this.columnDING_NDOCTO = new DataColumn("DING_NDOCTO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDING_NDOCTO);
                this.columnINGR_NCORR = new DataColumn("INGR_NCORR", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINGR_NCORR);
                this.columnTING_CCOD = new DataColumn("TING_CCOD", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTING_CCOD);
                this.columnCCTE_TDESC = new DataColumn("CCTE_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCCTE_TDESC);
                this.columnSEDE_TCALLE = new DataColumn("SEDE_TCALLE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSEDE_TCALLE);
                this.columnSEDE_TNRO = new DataColumn("SEDE_TNRO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSEDE_TNRO);
                this.columnCCTE_CCOD = new DataColumn("CCTE_CCOD", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCCTE_CCOD);
                this.columnSEDE_CCOD = new DataColumn("SEDE_CCOD", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSEDE_CCOD);
                this.columnESPE_TDESC = new DataColumn("ESPE_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnESPE_TDESC);
                this.columnEDIN_TDESC = new DataColumn("EDIN_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEDIN_TDESC);
                this.columnINGR_FPAGO = new DataColumn("INGR_FPAGO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINGR_FPAGO);
                this.columnENVI_NCORR.ReadOnly = true;
                this.columnENVI_FENVIO.ReadOnly = true;
                this.columnINEN_CCOD.ReadOnly = true;
                this.columnINEN_TDESC.ReadOnly = true;
                this.columnPLAZ_CCOD.ReadOnly = true;
                this.columnPLAZ_TDESC.ReadOnly = true;
                this.columnRUT_ALUMNO.ReadOnly = true;
                this.columnNOMBRE_APODERADO.ReadOnly = true;
                this.columnRUT_APODERADO.ReadOnly = true;
                this.columnDIRECCION.ReadOnly = true;
                this.columnDING_FDOCTO.ReadOnly = true;
                this.columnDING_MDETALLE.ReadOnly = true;
                this.columnDING_NDOCTO.ReadOnly = true;
                this.columnINGR_NCORR.ReadOnly = true;
                this.columnTING_CCOD.ReadOnly = true;
                this.columnCCTE_TDESC.ReadOnly = true;
                this.columnSEDE_TCALLE.ReadOnly = true;
                this.columnSEDE_TNRO.ReadOnly = true;
                this.columnCCTE_CCOD.ReadOnly = true;
                this.columnSEDE_CCOD.ReadOnly = true;
                this.columnESPE_TDESC.ReadOnly = true;
                this.columnEDIN_TDESC.ReadOnly = true;
                this.columnINGR_FPAGO.ReadOnly = true;
            }
            
            public _TableRow New_TableRow() {
                return ((_TableRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new _TableRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(_TableRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this._TableRowChanged != null)) {
                    this._TableRowChanged(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this._TableRowChanging != null)) {
                    this._TableRowChanging(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this._TableRowDeleted != null)) {
                    this._TableRowDeleted(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this._TableRowDeleting != null)) {
                    this._TableRowDeleting(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            public void Remove_TableRow(_TableRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRow : DataRow {
            
            private _TableDataTable table_Table;
            
            internal _TableRow(DataRowBuilder rb) : 
                    base(rb) {
                this.table_Table = ((_TableDataTable)(this.Table));
            }
            
            public string ENVI_NCORR {
                get {
                    try {
                        return ((string)(this[this.table_Table.ENVI_NCORRColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ENVI_NCORRColumn] = value;
                }
            }
            
            public string ENVI_FENVIO {
                get {
                    try {
                        return ((string)(this[this.table_Table.ENVI_FENVIOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ENVI_FENVIOColumn] = value;
                }
            }
            
            public string INEN_CCOD {
                get {
                    try {
                        return ((string)(this[this.table_Table.INEN_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.INEN_CCODColumn] = value;
                }
            }
            
            public string INEN_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.INEN_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.INEN_TDESCColumn] = value;
                }
            }
            
            public string PLAZ_CCOD {
                get {
                    try {
                        return ((string)(this[this.table_Table.PLAZ_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.PLAZ_CCODColumn] = value;
                }
            }
            
            public string PLAZ_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.PLAZ_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.PLAZ_TDESCColumn] = value;
                }
            }
            
            public string RUT_ALUMNO {
                get {
                    try {
                        return ((string)(this[this.table_Table.RUT_ALUMNOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.RUT_ALUMNOColumn] = value;
                }
            }
            
            public string NOMBRE_APODERADO {
                get {
                    try {
                        return ((string)(this[this.table_Table.NOMBRE_APODERADOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.NOMBRE_APODERADOColumn] = value;
                }
            }
            
            public string RUT_APODERADO {
                get {
                    try {
                        return ((string)(this[this.table_Table.RUT_APODERADOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.RUT_APODERADOColumn] = value;
                }
            }
            
            public string DIRECCION {
                get {
                    try {
                        return ((string)(this[this.table_Table.DIRECCIONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DIRECCIONColumn] = value;
                }
            }
            
            public string DING_FDOCTO {
                get {
                    try {
                        return ((string)(this[this.table_Table.DING_FDOCTOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DING_FDOCTOColumn] = value;
                }
            }
            
            public string DING_MDETALLE {
                get {
                    try {
                        return ((string)(this[this.table_Table.DING_MDETALLEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DING_MDETALLEColumn] = value;
                }
            }
            
            public string DING_NDOCTO {
                get {
                    try {
                        return ((string)(this[this.table_Table.DING_NDOCTOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DING_NDOCTOColumn] = value;
                }
            }
            
            public string INGR_NCORR {
                get {
                    try {
                        return ((string)(this[this.table_Table.INGR_NCORRColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.INGR_NCORRColumn] = value;
                }
            }
            
            public string TING_CCOD {
                get {
                    try {
                        return ((string)(this[this.table_Table.TING_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.TING_CCODColumn] = value;
                }
            }
            
            public string CCTE_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.CCTE_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CCTE_TDESCColumn] = value;
                }
            }
            
            public string SEDE_TCALLE {
                get {
                    try {
                        return ((string)(this[this.table_Table.SEDE_TCALLEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.SEDE_TCALLEColumn] = value;
                }
            }
            
            public string SEDE_TNRO {
                get {
                    try {
                        return ((string)(this[this.table_Table.SEDE_TNROColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.SEDE_TNROColumn] = value;
                }
            }
            
            public string CCTE_CCOD {
                get {
                    try {
                        return ((string)(this[this.table_Table.CCTE_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CCTE_CCODColumn] = value;
                }
            }
            
            public string SEDE_CCOD {
                get {
                    try {
                        return ((string)(this[this.table_Table.SEDE_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.SEDE_CCODColumn] = value;
                }
            }
            
            public string ESPE_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.ESPE_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ESPE_TDESCColumn] = value;
                }
            }
            
            public string EDIN_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.EDIN_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.EDIN_TDESCColumn] = value;
                }
            }
            
            public string INGR_FPAGO {
                get {
                    try {
                        return ((string)(this[this.table_Table.INGR_FPAGOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.INGR_FPAGOColumn] = value;
                }
            }
            
            public bool IsENVI_NCORRNull() {
                return this.IsNull(this.table_Table.ENVI_NCORRColumn);
            }
            
            public void SetENVI_NCORRNull() {
                this[this.table_Table.ENVI_NCORRColumn] = System.Convert.DBNull;
            }
            
            public bool IsENVI_FENVIONull() {
                return this.IsNull(this.table_Table.ENVI_FENVIOColumn);
            }
            
            public void SetENVI_FENVIONull() {
                this[this.table_Table.ENVI_FENVIOColumn] = System.Convert.DBNull;
            }
            
            public bool IsINEN_CCODNull() {
                return this.IsNull(this.table_Table.INEN_CCODColumn);
            }
            
            public void SetINEN_CCODNull() {
                this[this.table_Table.INEN_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsINEN_TDESCNull() {
                return this.IsNull(this.table_Table.INEN_TDESCColumn);
            }
            
            public void SetINEN_TDESCNull() {
                this[this.table_Table.INEN_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsPLAZ_CCODNull() {
                return this.IsNull(this.table_Table.PLAZ_CCODColumn);
            }
            
            public void SetPLAZ_CCODNull() {
                this[this.table_Table.PLAZ_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsPLAZ_TDESCNull() {
                return this.IsNull(this.table_Table.PLAZ_TDESCColumn);
            }
            
            public void SetPLAZ_TDESCNull() {
                this[this.table_Table.PLAZ_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsRUT_ALUMNONull() {
                return this.IsNull(this.table_Table.RUT_ALUMNOColumn);
            }
            
            public void SetRUT_ALUMNONull() {
                this[this.table_Table.RUT_ALUMNOColumn] = System.Convert.DBNull;
            }
            
            public bool IsNOMBRE_APODERADONull() {
                return this.IsNull(this.table_Table.NOMBRE_APODERADOColumn);
            }
            
            public void SetNOMBRE_APODERADONull() {
                this[this.table_Table.NOMBRE_APODERADOColumn] = System.Convert.DBNull;
            }
            
            public bool IsRUT_APODERADONull() {
                return this.IsNull(this.table_Table.RUT_APODERADOColumn);
            }
            
            public void SetRUT_APODERADONull() {
                this[this.table_Table.RUT_APODERADOColumn] = System.Convert.DBNull;
            }
            
            public bool IsDIRECCIONNull() {
                return this.IsNull(this.table_Table.DIRECCIONColumn);
            }
            
            public void SetDIRECCIONNull() {
                this[this.table_Table.DIRECCIONColumn] = System.Convert.DBNull;
            }
            
            public bool IsDING_FDOCTONull() {
                return this.IsNull(this.table_Table.DING_FDOCTOColumn);
            }
            
            public void SetDING_FDOCTONull() {
                this[this.table_Table.DING_FDOCTOColumn] = System.Convert.DBNull;
            }
            
            public bool IsDING_MDETALLENull() {
                return this.IsNull(this.table_Table.DING_MDETALLEColumn);
            }
            
            public void SetDING_MDETALLENull() {
                this[this.table_Table.DING_MDETALLEColumn] = System.Convert.DBNull;
            }
            
            public bool IsDING_NDOCTONull() {
                return this.IsNull(this.table_Table.DING_NDOCTOColumn);
            }
            
            public void SetDING_NDOCTONull() {
                this[this.table_Table.DING_NDOCTOColumn] = System.Convert.DBNull;
            }
            
            public bool IsINGR_NCORRNull() {
                return this.IsNull(this.table_Table.INGR_NCORRColumn);
            }
            
            public void SetINGR_NCORRNull() {
                this[this.table_Table.INGR_NCORRColumn] = System.Convert.DBNull;
            }
            
            public bool IsTING_CCODNull() {
                return this.IsNull(this.table_Table.TING_CCODColumn);
            }
            
            public void SetTING_CCODNull() {
                this[this.table_Table.TING_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsCCTE_TDESCNull() {
                return this.IsNull(this.table_Table.CCTE_TDESCColumn);
            }
            
            public void SetCCTE_TDESCNull() {
                this[this.table_Table.CCTE_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsSEDE_TCALLENull() {
                return this.IsNull(this.table_Table.SEDE_TCALLEColumn);
            }
            
            public void SetSEDE_TCALLENull() {
                this[this.table_Table.SEDE_TCALLEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSEDE_TNRONull() {
                return this.IsNull(this.table_Table.SEDE_TNROColumn);
            }
            
            public void SetSEDE_TNRONull() {
                this[this.table_Table.SEDE_TNROColumn] = System.Convert.DBNull;
            }
            
            public bool IsCCTE_CCODNull() {
                return this.IsNull(this.table_Table.CCTE_CCODColumn);
            }
            
            public void SetCCTE_CCODNull() {
                this[this.table_Table.CCTE_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsSEDE_CCODNull() {
                return this.IsNull(this.table_Table.SEDE_CCODColumn);
            }
            
            public void SetSEDE_CCODNull() {
                this[this.table_Table.SEDE_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsESPE_TDESCNull() {
                return this.IsNull(this.table_Table.ESPE_TDESCColumn);
            }
            
            public void SetESPE_TDESCNull() {
                this[this.table_Table.ESPE_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsEDIN_TDESCNull() {
                return this.IsNull(this.table_Table.EDIN_TDESCColumn);
            }
            
            public void SetEDIN_TDESCNull() {
                this[this.table_Table.EDIN_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsINGR_FPAGONull() {
                return this.IsNull(this.table_Table.INGR_FPAGOColumn);
            }
            
            public void SetINGR_FPAGONull() {
                this[this.table_Table.INGR_FPAGOColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRowChangeEvent : EventArgs {
            
            private _TableRow eventRow;
            
            private DataRowAction eventAction;
            
            public _TableRowChangeEvent(_TableRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public _TableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
