insert into sis_roles_usuarios values (256114, 1  , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 2  , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 3  , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 4  , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 5  , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 7  , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 21 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 23 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 24 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 25 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 27 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 28 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 29 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 32 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 33 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 35 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 36 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 37 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 38 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 39 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 42 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 44 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 45 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 47 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 48 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 49 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 50 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 51 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 52 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 54 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 60 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 61 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 62 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 63 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 64 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 65 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 66 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 68 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 69 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 70 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 71 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 72 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 73 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 74 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 75 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 76 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 77 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 78 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 79 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 80 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 81 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 82 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 83 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 86 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 87 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 88 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 89 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 90 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 91 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 92 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 94 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 95 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 96 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 97 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 98 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 99 , getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 100, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 101, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 102, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 103, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 104, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 105, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 106, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 107, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 109, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 110, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 111, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 112, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 113, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 114, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 115, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 116, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 117, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 118, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 120, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 121, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 122, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 123, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 124, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 125, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 127, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 128, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 129, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 134, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 135, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 136, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 137, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 138, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 139, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 140, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 141, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 142, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 143, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 144, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 145, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 146, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 147, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 148, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 149, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 150, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 152, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 153, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 154, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 155, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 156, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 157, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 158, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 159, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 160, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 161, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 162, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 163, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 164, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 165, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 166, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 168, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 169, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 170, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 171, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 175, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 176, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 177, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 178, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 179, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 180, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 181, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 182, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 183, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 184, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 186, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 187, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 188, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 189, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 190, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 191, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 192, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 193, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 194, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 195, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 196, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 197, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 198, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 199, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 201, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 202, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 203, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 204, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 206, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 207, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 208, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 209, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 210, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 211, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 212, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 214, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 215, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 216, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 217, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 218, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 219, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 220, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 221, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 222, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 223, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 224, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 225, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 226, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 227, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 228, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 229, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 230, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 231, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 232, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 233, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 234, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 235, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 236, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 237, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 239, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 240, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 241, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 243, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 244, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 245, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 246, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 247, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 248, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 249, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 253, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 254, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 255, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 260, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 261, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 262, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 263, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 264, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 265, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 266, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 267, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 268, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 269, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 270, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 271, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 272, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 273, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 274, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 275, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 276, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 277, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 278, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 279, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 280, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 281, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 282, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 283, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 284, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 285, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 286, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 287, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 288, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 289, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 290, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 291, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 292, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 293, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 294, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 295, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 296, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 297, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 298, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 299, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 302, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 306, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 307, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 308, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 310, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 311, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 312, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 314, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 315, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 316, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 318, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 319, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 320, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 321, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 322, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 323, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 324, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 325, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 326, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 327, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 328, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 329, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 330, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 331, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 332, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 333, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 334, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 335, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 336, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 337, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 338, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 339, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 340, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 341, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 342, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 347, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 348, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 349, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 351, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 352, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 353, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 354, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 355, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 356, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 357, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 358, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 359, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 360, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 361, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 362, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 363, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 364, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 365, getdate(), 'lherrerag', getdate() )
insert into sis_roles_usuarios values (256114, 366, getdate(), 'lherrerag', getdate() )