INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 74, 1, 184681, 1, 'mriffo' ) 
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 76, 1, 184856, 1, 'mriffo' )
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 77, 1, 184857, 1, 'mriffo' )
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 78, 1, 184858, 1, 'mriffo' )    
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 79, 1, 184859, 1, 'mriffo' )    
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 80, 1, 184862, 1, 'mriffo' )
lyon   
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 75, 2, 184855, 1, 'mriffo' )
melipilla
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 81, 4, 184860, 1, 'mriffo' )   
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 82, 4, 184861, 1, 'mriffo' )   
baquedano
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 83, 8, 184685, 1, 'mriffo' )   
INSERT INTO dbo.CAJEROS ( CAJE_CCOD, SEDE_CCOD, PERS_NCORR, CAJE_CESTADO, AUDI_TUSUARIO ) VALUES ( 84, 8, 184552, 1, 'mriffo' )   

