//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace imprimir_anexos {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class contratos : DataSet {
        
        private _TableDataTable table_Table;
        
        public contratos() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected contratos(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Table"] != null)) {
                    this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public _TableDataTable _Table {
            get {
                return this.table_Table;
            }
        }
        
        public override DataSet Clone() {
            contratos cln = ((contratos)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Table"] != null)) {
                this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.table_Table = ((_TableDataTable)(this.Tables["Table"]));
            if ((this.table_Table != null)) {
                this.table_Table.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "contratos";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/contratos.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.table_Table = new _TableDataTable();
            this.Tables.Add(this.table_Table);
        }
        
        private bool ShouldSerialize_Table() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void _TableRowChangeEventHandler(object sender, _TableRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCDOC_NCORR;
            
            private DataColumn columnpers_ncorr;
            
            private DataColumn columnNombre_Docente;
            
            private DataColumn columnRut_Docente;
            
            private DataColumn columnDV;
            
            private DataColumn columnFecha_Nac;
            
            private DataColumn columnEstado_Civil;
            
            private DataColumn columnDireccion;
            
            private DataColumn columnComuna;
            
            private DataColumn columnCiudad;
            
            private DataColumn columnPROFESION;
            
            private DataColumn columnBLOQ_ANEXO;
            
            private DataColumn columnCARR_CCOD;
            
            private DataColumn columnCARR_TDESC;
            
            private DataColumn columnASIG_CCOD;
            
            private DataColumn columnASIG_NHORAS;
            
            private DataColumn columnASIG_TDESC;
            
            private DataColumn columnDUAS_TDESC;
            
            private DataColumn columnmonto_sesion;
            
            private DataColumn columnValor;
            
            private DataColumn columnINST_TRAZON_SOCIAL;
            
            private DataColumn columnNombreRepLeg;
            
            private DataColumn columnTipoDocente;
            
            private DataColumn columnNacionalidad;
            
            private DataColumn columnFechaI;
            
            private DataColumn columnFechaF;
            
            private DataColumn columnhoras_coordinacion;
            
            private DataColumn columnSECC_TDESC;
            
            private DataColumn columnsede_tdesc;
            
            private DataColumn columnnum_cuotas;
            
            private DataColumn columnfecha_inicio;
            
            private DataColumn columnfecha_fin;
            
            private DataColumn columnporcentaje;
            
            private DataColumn columnmonto_colacion;
            
            private DataColumn columninstitucion_t;
            
            private DataColumn columngrado;
            
            private DataColumn columninstitucion_g;
            
            private DataColumn columnhorario;
            
            internal _TableDataTable() : 
                    base("Table") {
                this.InitClass();
            }
            
            internal _TableDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CDOC_NCORRColumn {
                get {
                    return this.columnCDOC_NCORR;
                }
            }
            
            internal DataColumn pers_ncorrColumn {
                get {
                    return this.columnpers_ncorr;
                }
            }
            
            internal DataColumn Nombre_DocenteColumn {
                get {
                    return this.columnNombre_Docente;
                }
            }
            
            internal DataColumn Rut_DocenteColumn {
                get {
                    return this.columnRut_Docente;
                }
            }
            
            internal DataColumn DVColumn {
                get {
                    return this.columnDV;
                }
            }
            
            internal DataColumn Fecha_NacColumn {
                get {
                    return this.columnFecha_Nac;
                }
            }
            
            internal DataColumn Estado_CivilColumn {
                get {
                    return this.columnEstado_Civil;
                }
            }
            
            internal DataColumn DireccionColumn {
                get {
                    return this.columnDireccion;
                }
            }
            
            internal DataColumn ComunaColumn {
                get {
                    return this.columnComuna;
                }
            }
            
            internal DataColumn CiudadColumn {
                get {
                    return this.columnCiudad;
                }
            }
            
            internal DataColumn PROFESIONColumn {
                get {
                    return this.columnPROFESION;
                }
            }
            
            internal DataColumn BLOQ_ANEXOColumn {
                get {
                    return this.columnBLOQ_ANEXO;
                }
            }
            
            internal DataColumn CARR_CCODColumn {
                get {
                    return this.columnCARR_CCOD;
                }
            }
            
            internal DataColumn CARR_TDESCColumn {
                get {
                    return this.columnCARR_TDESC;
                }
            }
            
            internal DataColumn ASIG_CCODColumn {
                get {
                    return this.columnASIG_CCOD;
                }
            }
            
            internal DataColumn ASIG_NHORASColumn {
                get {
                    return this.columnASIG_NHORAS;
                }
            }
            
            internal DataColumn ASIG_TDESCColumn {
                get {
                    return this.columnASIG_TDESC;
                }
            }
            
            internal DataColumn DUAS_TDESCColumn {
                get {
                    return this.columnDUAS_TDESC;
                }
            }
            
            internal DataColumn monto_sesionColumn {
                get {
                    return this.columnmonto_sesion;
                }
            }
            
            internal DataColumn ValorColumn {
                get {
                    return this.columnValor;
                }
            }
            
            internal DataColumn INST_TRAZON_SOCIALColumn {
                get {
                    return this.columnINST_TRAZON_SOCIAL;
                }
            }
            
            internal DataColumn NombreRepLegColumn {
                get {
                    return this.columnNombreRepLeg;
                }
            }
            
            internal DataColumn TipoDocenteColumn {
                get {
                    return this.columnTipoDocente;
                }
            }
            
            internal DataColumn NacionalidadColumn {
                get {
                    return this.columnNacionalidad;
                }
            }
            
            internal DataColumn FechaIColumn {
                get {
                    return this.columnFechaI;
                }
            }
            
            internal DataColumn FechaFColumn {
                get {
                    return this.columnFechaF;
                }
            }
            
            internal DataColumn horas_coordinacionColumn {
                get {
                    return this.columnhoras_coordinacion;
                }
            }
            
            internal DataColumn SECC_TDESCColumn {
                get {
                    return this.columnSECC_TDESC;
                }
            }
            
            internal DataColumn sede_tdescColumn {
                get {
                    return this.columnsede_tdesc;
                }
            }
            
            internal DataColumn num_cuotasColumn {
                get {
                    return this.columnnum_cuotas;
                }
            }
            
            internal DataColumn fecha_inicioColumn {
                get {
                    return this.columnfecha_inicio;
                }
            }
            
            internal DataColumn fecha_finColumn {
                get {
                    return this.columnfecha_fin;
                }
            }
            
            internal DataColumn porcentajeColumn {
                get {
                    return this.columnporcentaje;
                }
            }
            
            internal DataColumn monto_colacionColumn {
                get {
                    return this.columnmonto_colacion;
                }
            }
            
            internal DataColumn institucion_tColumn {
                get {
                    return this.columninstitucion_t;
                }
            }
            
            internal DataColumn gradoColumn {
                get {
                    return this.columngrado;
                }
            }
            
            internal DataColumn institucion_gColumn {
                get {
                    return this.columninstitucion_g;
                }
            }
            
            internal DataColumn horarioColumn {
                get {
                    return this.columnhorario;
                }
            }
            
            public _TableRow this[int index] {
                get {
                    return ((_TableRow)(this.Rows[index]));
                }
            }
            
            public event _TableRowChangeEventHandler _TableRowChanged;
            
            public event _TableRowChangeEventHandler _TableRowChanging;
            
            public event _TableRowChangeEventHandler _TableRowDeleted;
            
            public event _TableRowChangeEventHandler _TableRowDeleting;
            
            public void Add_TableRow(_TableRow row) {
                this.Rows.Add(row);
            }
            
            public _TableRow Add_TableRow(
                        int CDOC_NCORR, 
                        int pers_ncorr, 
                        string Nombre_Docente, 
                        int Rut_Docente, 
                        string DV, 
                        string Fecha_Nac, 
                        string Estado_Civil, 
                        string Direccion, 
                        string Comuna, 
                        string Ciudad, 
                        string PROFESION, 
                        int BLOQ_ANEXO, 
                        int CARR_CCOD, 
                        string CARR_TDESC, 
                        string ASIG_CCOD, 
                        int ASIG_NHORAS, 
                        string ASIG_TDESC, 
                        string DUAS_TDESC, 
                        int monto_sesion, 
                        int Valor, 
                        string INST_TRAZON_SOCIAL, 
                        string NombreRepLeg, 
                        string TipoDocente, 
                        string Nacionalidad, 
                        string FechaI, 
                        string FechaF, 
                        int horas_coordinacion, 
                        string SECC_TDESC, 
                        string sede_tdesc, 
                        string num_cuotas, 
                        string fecha_inicio, 
                        string fecha_fin, 
                        string porcentaje, 
                        string monto_colacion, 
                        string institucion_t, 
                        string grado, 
                        string institucion_g, 
                        string horario) {
                _TableRow row_TableRow = ((_TableRow)(this.NewRow()));
                row_TableRow.ItemArray = new object[] {
                        CDOC_NCORR,
                        pers_ncorr,
                        Nombre_Docente,
                        Rut_Docente,
                        DV,
                        Fecha_Nac,
                        Estado_Civil,
                        Direccion,
                        Comuna,
                        Ciudad,
                        PROFESION,
                        BLOQ_ANEXO,
                        CARR_CCOD,
                        CARR_TDESC,
                        ASIG_CCOD,
                        ASIG_NHORAS,
                        ASIG_TDESC,
                        DUAS_TDESC,
                        monto_sesion,
                        Valor,
                        INST_TRAZON_SOCIAL,
                        NombreRepLeg,
                        TipoDocente,
                        Nacionalidad,
                        FechaI,
                        FechaF,
                        horas_coordinacion,
                        SECC_TDESC,
                        sede_tdesc,
                        num_cuotas,
                        fecha_inicio,
                        fecha_fin,
                        porcentaje,
                        monto_colacion,
                        institucion_t,
                        grado,
                        institucion_g,
                        horario};
                this.Rows.Add(row_TableRow);
                return row_TableRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                _TableDataTable cln = ((_TableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new _TableDataTable();
            }
            
            internal void InitVars() {
                this.columnCDOC_NCORR = this.Columns["CDOC_NCORR"];
                this.columnpers_ncorr = this.Columns["pers_ncorr"];
                this.columnNombre_Docente = this.Columns["Nombre_Docente"];
                this.columnRut_Docente = this.Columns["Rut_Docente"];
                this.columnDV = this.Columns["DV"];
                this.columnFecha_Nac = this.Columns["Fecha_Nac"];
                this.columnEstado_Civil = this.Columns["Estado_Civil"];
                this.columnDireccion = this.Columns["Direccion"];
                this.columnComuna = this.Columns["Comuna"];
                this.columnCiudad = this.Columns["Ciudad"];
                this.columnPROFESION = this.Columns["PROFESION"];
                this.columnBLOQ_ANEXO = this.Columns["BLOQ_ANEXO"];
                this.columnCARR_CCOD = this.Columns["CARR_CCOD"];
                this.columnCARR_TDESC = this.Columns["CARR_TDESC"];
                this.columnASIG_CCOD = this.Columns["ASIG_CCOD"];
                this.columnASIG_NHORAS = this.Columns["ASIG_NHORAS"];
                this.columnASIG_TDESC = this.Columns["ASIG_TDESC"];
                this.columnDUAS_TDESC = this.Columns["DUAS_TDESC"];
                this.columnmonto_sesion = this.Columns["monto_sesion"];
                this.columnValor = this.Columns["Valor"];
                this.columnINST_TRAZON_SOCIAL = this.Columns["INST_TRAZON_SOCIAL"];
                this.columnNombreRepLeg = this.Columns["NombreRepLeg"];
                this.columnTipoDocente = this.Columns["TipoDocente"];
                this.columnNacionalidad = this.Columns["Nacionalidad"];
                this.columnFechaI = this.Columns["FechaI"];
                this.columnFechaF = this.Columns["FechaF"];
                this.columnhoras_coordinacion = this.Columns["horas_coordinacion"];
                this.columnSECC_TDESC = this.Columns["SECC_TDESC"];
                this.columnsede_tdesc = this.Columns["sede_tdesc"];
                this.columnnum_cuotas = this.Columns["num_cuotas"];
                this.columnfecha_inicio = this.Columns["fecha_inicio"];
                this.columnfecha_fin = this.Columns["fecha_fin"];
                this.columnporcentaje = this.Columns["porcentaje"];
                this.columnmonto_colacion = this.Columns["monto_colacion"];
                this.columninstitucion_t = this.Columns["institucion_t"];
                this.columngrado = this.Columns["grado"];
                this.columninstitucion_g = this.Columns["institucion_g"];
                this.columnhorario = this.Columns["horario"];
            }
            
            private void InitClass() {
                this.columnCDOC_NCORR = new DataColumn("CDOC_NCORR", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCDOC_NCORR);
                this.columnpers_ncorr = new DataColumn("pers_ncorr", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpers_ncorr);
                this.columnNombre_Docente = new DataColumn("Nombre_Docente", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNombre_Docente);
                this.columnRut_Docente = new DataColumn("Rut_Docente", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRut_Docente);
                this.columnDV = new DataColumn("DV", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDV);
                this.columnFecha_Nac = new DataColumn("Fecha_Nac", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFecha_Nac);
                this.columnEstado_Civil = new DataColumn("Estado_Civil", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEstado_Civil);
                this.columnDireccion = new DataColumn("Direccion", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDireccion);
                this.columnComuna = new DataColumn("Comuna", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnComuna);
                this.columnCiudad = new DataColumn("Ciudad", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCiudad);
                this.columnPROFESION = new DataColumn("PROFESION", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPROFESION);
                this.columnBLOQ_ANEXO = new DataColumn("BLOQ_ANEXO", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBLOQ_ANEXO);
                this.columnCARR_CCOD = new DataColumn("CARR_CCOD", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCARR_CCOD);
                this.columnCARR_TDESC = new DataColumn("CARR_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCARR_TDESC);
                this.columnASIG_CCOD = new DataColumn("ASIG_CCOD", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnASIG_CCOD);
                this.columnASIG_NHORAS = new DataColumn("ASIG_NHORAS", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnASIG_NHORAS);
                this.columnASIG_TDESC = new DataColumn("ASIG_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnASIG_TDESC);
                this.columnDUAS_TDESC = new DataColumn("DUAS_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDUAS_TDESC);
                this.columnmonto_sesion = new DataColumn("monto_sesion", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmonto_sesion);
                this.columnValor = new DataColumn("Valor", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnValor);
                this.columnINST_TRAZON_SOCIAL = new DataColumn("INST_TRAZON_SOCIAL", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnINST_TRAZON_SOCIAL);
                this.columnNombreRepLeg = new DataColumn("NombreRepLeg", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNombreRepLeg);
                this.columnTipoDocente = new DataColumn("TipoDocente", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTipoDocente);
                this.columnNacionalidad = new DataColumn("Nacionalidad", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNacionalidad);
                this.columnFechaI = new DataColumn("FechaI", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaI);
                this.columnFechaF = new DataColumn("FechaF", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFechaF);
                this.columnhoras_coordinacion = new DataColumn("horas_coordinacion", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnhoras_coordinacion);
                this.columnSECC_TDESC = new DataColumn("SECC_TDESC", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSECC_TDESC);
                this.columnsede_tdesc = new DataColumn("sede_tdesc", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnsede_tdesc);
                this.columnnum_cuotas = new DataColumn("num_cuotas", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_cuotas);
                this.columnfecha_inicio = new DataColumn("fecha_inicio", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnfecha_inicio);
                this.columnfecha_fin = new DataColumn("fecha_fin", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnfecha_fin);
                this.columnporcentaje = new DataColumn("porcentaje", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnporcentaje);
                this.columnmonto_colacion = new DataColumn("monto_colacion", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmonto_colacion);
                this.columninstitucion_t = new DataColumn("institucion_t", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columninstitucion_t);
                this.columngrado = new DataColumn("grado", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngrado);
                this.columninstitucion_g = new DataColumn("institucion_g", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columninstitucion_g);
                this.columnhorario = new DataColumn("horario", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnhorario);
                this.columnCDOC_NCORR.ReadOnly = true;
                this.columnpers_ncorr.ReadOnly = true;
                this.columnNombre_Docente.ReadOnly = true;
                this.columnRut_Docente.ReadOnly = true;
                this.columnDV.ReadOnly = true;
                this.columnFecha_Nac.ReadOnly = true;
                this.columnEstado_Civil.ReadOnly = true;
                this.columnDireccion.ReadOnly = true;
                this.columnComuna.ReadOnly = true;
                this.columnCiudad.ReadOnly = true;
                this.columnPROFESION.ReadOnly = true;
                this.columnBLOQ_ANEXO.ReadOnly = true;
                this.columnCARR_CCOD.ReadOnly = true;
                this.columnCARR_TDESC.ReadOnly = true;
                this.columnASIG_CCOD.ReadOnly = true;
                this.columnASIG_NHORAS.ReadOnly = true;
                this.columnASIG_TDESC.ReadOnly = true;
                this.columnDUAS_TDESC.ReadOnly = true;
                this.columnmonto_sesion.ReadOnly = true;
                this.columnValor.ReadOnly = true;
                this.columnINST_TRAZON_SOCIAL.ReadOnly = true;
                this.columnNombreRepLeg.ReadOnly = true;
                this.columnTipoDocente.ReadOnly = true;
                this.columnNacionalidad.ReadOnly = true;
                this.columnFechaI.ReadOnly = true;
                this.columnFechaF.ReadOnly = true;
                this.columnhoras_coordinacion.ReadOnly = true;
                this.columnSECC_TDESC.ReadOnly = true;
                this.columnsede_tdesc.ReadOnly = true;
                this.columnnum_cuotas.ReadOnly = true;
                this.columnfecha_inicio.ReadOnly = true;
                this.columnfecha_fin.ReadOnly = true;
                this.columnporcentaje.ReadOnly = true;
                this.columnmonto_colacion.ReadOnly = true;
                this.columninstitucion_t.ReadOnly = true;
                this.columngrado.ReadOnly = true;
                this.columninstitucion_g.ReadOnly = true;
                this.columnhorario.ReadOnly = true;
            }
            
            public _TableRow New_TableRow() {
                return ((_TableRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new _TableRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(_TableRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this._TableRowChanged != null)) {
                    this._TableRowChanged(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this._TableRowChanging != null)) {
                    this._TableRowChanging(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this._TableRowDeleted != null)) {
                    this._TableRowDeleted(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this._TableRowDeleting != null)) {
                    this._TableRowDeleting(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            public void Remove_TableRow(_TableRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRow : DataRow {
            
            private _TableDataTable table_Table;
            
            internal _TableRow(DataRowBuilder rb) : 
                    base(rb) {
                this.table_Table = ((_TableDataTable)(this.Table));
            }
            
            public int CDOC_NCORR {
                get {
                    try {
                        return ((int)(this[this.table_Table.CDOC_NCORRColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CDOC_NCORRColumn] = value;
                }
            }
            
            public int pers_ncorr {
                get {
                    try {
                        return ((int)(this[this.table_Table.pers_ncorrColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.pers_ncorrColumn] = value;
                }
            }
            
            public string Nombre_Docente {
                get {
                    try {
                        return ((string)(this[this.table_Table.Nombre_DocenteColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.Nombre_DocenteColumn] = value;
                }
            }
            
            public int Rut_Docente {
                get {
                    try {
                        return ((int)(this[this.table_Table.Rut_DocenteColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.Rut_DocenteColumn] = value;
                }
            }
            
            public string DV {
                get {
                    try {
                        return ((string)(this[this.table_Table.DVColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DVColumn] = value;
                }
            }
            
            public string Fecha_Nac {
                get {
                    try {
                        return ((string)(this[this.table_Table.Fecha_NacColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.Fecha_NacColumn] = value;
                }
            }
            
            public string Estado_Civil {
                get {
                    try {
                        return ((string)(this[this.table_Table.Estado_CivilColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.Estado_CivilColumn] = value;
                }
            }
            
            public string Direccion {
                get {
                    try {
                        return ((string)(this[this.table_Table.DireccionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DireccionColumn] = value;
                }
            }
            
            public string Comuna {
                get {
                    try {
                        return ((string)(this[this.table_Table.ComunaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ComunaColumn] = value;
                }
            }
            
            public string Ciudad {
                get {
                    try {
                        return ((string)(this[this.table_Table.CiudadColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CiudadColumn] = value;
                }
            }
            
            public string PROFESION {
                get {
                    try {
                        return ((string)(this[this.table_Table.PROFESIONColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.PROFESIONColumn] = value;
                }
            }
            
            public int BLOQ_ANEXO {
                get {
                    try {
                        return ((int)(this[this.table_Table.BLOQ_ANEXOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.BLOQ_ANEXOColumn] = value;
                }
            }
            
            public int CARR_CCOD {
                get {
                    try {
                        return ((int)(this[this.table_Table.CARR_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CARR_CCODColumn] = value;
                }
            }
            
            public string CARR_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.CARR_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CARR_TDESCColumn] = value;
                }
            }
            
            public string ASIG_CCOD {
                get {
                    try {
                        return ((string)(this[this.table_Table.ASIG_CCODColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ASIG_CCODColumn] = value;
                }
            }
            
            public int ASIG_NHORAS {
                get {
                    try {
                        return ((int)(this[this.table_Table.ASIG_NHORASColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ASIG_NHORASColumn] = value;
                }
            }
            
            public string ASIG_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.ASIG_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ASIG_TDESCColumn] = value;
                }
            }
            
            public string DUAS_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.DUAS_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DUAS_TDESCColumn] = value;
                }
            }
            
            public int monto_sesion {
                get {
                    try {
                        return ((int)(this[this.table_Table.monto_sesionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.monto_sesionColumn] = value;
                }
            }
            
            public int Valor {
                get {
                    try {
                        return ((int)(this[this.table_Table.ValorColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ValorColumn] = value;
                }
            }
            
            public string INST_TRAZON_SOCIAL {
                get {
                    try {
                        return ((string)(this[this.table_Table.INST_TRAZON_SOCIALColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.INST_TRAZON_SOCIALColumn] = value;
                }
            }
            
            public string NombreRepLeg {
                get {
                    try {
                        return ((string)(this[this.table_Table.NombreRepLegColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.NombreRepLegColumn] = value;
                }
            }
            
            public string TipoDocente {
                get {
                    try {
                        return ((string)(this[this.table_Table.TipoDocenteColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.TipoDocenteColumn] = value;
                }
            }
            
            public string Nacionalidad {
                get {
                    try {
                        return ((string)(this[this.table_Table.NacionalidadColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.NacionalidadColumn] = value;
                }
            }
            
            public string FechaI {
                get {
                    try {
                        return ((string)(this[this.table_Table.FechaIColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.FechaIColumn] = value;
                }
            }
            
            public string FechaF {
                get {
                    try {
                        return ((string)(this[this.table_Table.FechaFColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.FechaFColumn] = value;
                }
            }
            
            public int horas_coordinacion {
                get {
                    try {
                        return ((int)(this[this.table_Table.horas_coordinacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.horas_coordinacionColumn] = value;
                }
            }
            
            public string SECC_TDESC {
                get {
                    try {
                        return ((string)(this[this.table_Table.SECC_TDESCColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.SECC_TDESCColumn] = value;
                }
            }
            
            public string sede_tdesc {
                get {
                    try {
                        return ((string)(this[this.table_Table.sede_tdescColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.sede_tdescColumn] = value;
                }
            }
            
            public string num_cuotas {
                get {
                    try {
                        return ((string)(this[this.table_Table.num_cuotasColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.num_cuotasColumn] = value;
                }
            }
            
            public string fecha_inicio {
                get {
                    try {
                        return ((string)(this[this.table_Table.fecha_inicioColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.fecha_inicioColumn] = value;
                }
            }
            
            public string fecha_fin {
                get {
                    try {
                        return ((string)(this[this.table_Table.fecha_finColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.fecha_finColumn] = value;
                }
            }
            
            public string porcentaje {
                get {
                    try {
                        return ((string)(this[this.table_Table.porcentajeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.porcentajeColumn] = value;
                }
            }
            
            public string monto_colacion {
                get {
                    try {
                        return ((string)(this[this.table_Table.monto_colacionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.monto_colacionColumn] = value;
                }
            }
            
            public string institucion_t {
                get {
                    try {
                        return ((string)(this[this.table_Table.institucion_tColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.institucion_tColumn] = value;
                }
            }
            
            public string grado {
                get {
                    try {
                        return ((string)(this[this.table_Table.gradoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.gradoColumn] = value;
                }
            }
            
            public string institucion_g {
                get {
                    try {
                        return ((string)(this[this.table_Table.institucion_gColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.institucion_gColumn] = value;
                }
            }
            
            public string horario {
                get {
                    try {
                        return ((string)(this[this.table_Table.horarioColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("No se puede obtener el valor porque es DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.horarioColumn] = value;
                }
            }
            
            public bool IsCDOC_NCORRNull() {
                return this.IsNull(this.table_Table.CDOC_NCORRColumn);
            }
            
            public void SetCDOC_NCORRNull() {
                this[this.table_Table.CDOC_NCORRColumn] = System.Convert.DBNull;
            }
            
            public bool Ispers_ncorrNull() {
                return this.IsNull(this.table_Table.pers_ncorrColumn);
            }
            
            public void Setpers_ncorrNull() {
                this[this.table_Table.pers_ncorrColumn] = System.Convert.DBNull;
            }
            
            public bool IsNombre_DocenteNull() {
                return this.IsNull(this.table_Table.Nombre_DocenteColumn);
            }
            
            public void SetNombre_DocenteNull() {
                this[this.table_Table.Nombre_DocenteColumn] = System.Convert.DBNull;
            }
            
            public bool IsRut_DocenteNull() {
                return this.IsNull(this.table_Table.Rut_DocenteColumn);
            }
            
            public void SetRut_DocenteNull() {
                this[this.table_Table.Rut_DocenteColumn] = System.Convert.DBNull;
            }
            
            public bool IsDVNull() {
                return this.IsNull(this.table_Table.DVColumn);
            }
            
            public void SetDVNull() {
                this[this.table_Table.DVColumn] = System.Convert.DBNull;
            }
            
            public bool IsFecha_NacNull() {
                return this.IsNull(this.table_Table.Fecha_NacColumn);
            }
            
            public void SetFecha_NacNull() {
                this[this.table_Table.Fecha_NacColumn] = System.Convert.DBNull;
            }
            
            public bool IsEstado_CivilNull() {
                return this.IsNull(this.table_Table.Estado_CivilColumn);
            }
            
            public void SetEstado_CivilNull() {
                this[this.table_Table.Estado_CivilColumn] = System.Convert.DBNull;
            }
            
            public bool IsDireccionNull() {
                return this.IsNull(this.table_Table.DireccionColumn);
            }
            
            public void SetDireccionNull() {
                this[this.table_Table.DireccionColumn] = System.Convert.DBNull;
            }
            
            public bool IsComunaNull() {
                return this.IsNull(this.table_Table.ComunaColumn);
            }
            
            public void SetComunaNull() {
                this[this.table_Table.ComunaColumn] = System.Convert.DBNull;
            }
            
            public bool IsCiudadNull() {
                return this.IsNull(this.table_Table.CiudadColumn);
            }
            
            public void SetCiudadNull() {
                this[this.table_Table.CiudadColumn] = System.Convert.DBNull;
            }
            
            public bool IsPROFESIONNull() {
                return this.IsNull(this.table_Table.PROFESIONColumn);
            }
            
            public void SetPROFESIONNull() {
                this[this.table_Table.PROFESIONColumn] = System.Convert.DBNull;
            }
            
            public bool IsBLOQ_ANEXONull() {
                return this.IsNull(this.table_Table.BLOQ_ANEXOColumn);
            }
            
            public void SetBLOQ_ANEXONull() {
                this[this.table_Table.BLOQ_ANEXOColumn] = System.Convert.DBNull;
            }
            
            public bool IsCARR_CCODNull() {
                return this.IsNull(this.table_Table.CARR_CCODColumn);
            }
            
            public void SetCARR_CCODNull() {
                this[this.table_Table.CARR_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsCARR_TDESCNull() {
                return this.IsNull(this.table_Table.CARR_TDESCColumn);
            }
            
            public void SetCARR_TDESCNull() {
                this[this.table_Table.CARR_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsASIG_CCODNull() {
                return this.IsNull(this.table_Table.ASIG_CCODColumn);
            }
            
            public void SetASIG_CCODNull() {
                this[this.table_Table.ASIG_CCODColumn] = System.Convert.DBNull;
            }
            
            public bool IsASIG_NHORASNull() {
                return this.IsNull(this.table_Table.ASIG_NHORASColumn);
            }
            
            public void SetASIG_NHORASNull() {
                this[this.table_Table.ASIG_NHORASColumn] = System.Convert.DBNull;
            }
            
            public bool IsASIG_TDESCNull() {
                return this.IsNull(this.table_Table.ASIG_TDESCColumn);
            }
            
            public void SetASIG_TDESCNull() {
                this[this.table_Table.ASIG_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool IsDUAS_TDESCNull() {
                return this.IsNull(this.table_Table.DUAS_TDESCColumn);
            }
            
            public void SetDUAS_TDESCNull() {
                this[this.table_Table.DUAS_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool Ismonto_sesionNull() {
                return this.IsNull(this.table_Table.monto_sesionColumn);
            }
            
            public void Setmonto_sesionNull() {
                this[this.table_Table.monto_sesionColumn] = System.Convert.DBNull;
            }
            
            public bool IsValorNull() {
                return this.IsNull(this.table_Table.ValorColumn);
            }
            
            public void SetValorNull() {
                this[this.table_Table.ValorColumn] = System.Convert.DBNull;
            }
            
            public bool IsINST_TRAZON_SOCIALNull() {
                return this.IsNull(this.table_Table.INST_TRAZON_SOCIALColumn);
            }
            
            public void SetINST_TRAZON_SOCIALNull() {
                this[this.table_Table.INST_TRAZON_SOCIALColumn] = System.Convert.DBNull;
            }
            
            public bool IsNombreRepLegNull() {
                return this.IsNull(this.table_Table.NombreRepLegColumn);
            }
            
            public void SetNombreRepLegNull() {
                this[this.table_Table.NombreRepLegColumn] = System.Convert.DBNull;
            }
            
            public bool IsTipoDocenteNull() {
                return this.IsNull(this.table_Table.TipoDocenteColumn);
            }
            
            public void SetTipoDocenteNull() {
                this[this.table_Table.TipoDocenteColumn] = System.Convert.DBNull;
            }
            
            public bool IsNacionalidadNull() {
                return this.IsNull(this.table_Table.NacionalidadColumn);
            }
            
            public void SetNacionalidadNull() {
                this[this.table_Table.NacionalidadColumn] = System.Convert.DBNull;
            }
            
            public bool IsFechaINull() {
                return this.IsNull(this.table_Table.FechaIColumn);
            }
            
            public void SetFechaINull() {
                this[this.table_Table.FechaIColumn] = System.Convert.DBNull;
            }
            
            public bool IsFechaFNull() {
                return this.IsNull(this.table_Table.FechaFColumn);
            }
            
            public void SetFechaFNull() {
                this[this.table_Table.FechaFColumn] = System.Convert.DBNull;
            }
            
            public bool Ishoras_coordinacionNull() {
                return this.IsNull(this.table_Table.horas_coordinacionColumn);
            }
            
            public void Sethoras_coordinacionNull() {
                this[this.table_Table.horas_coordinacionColumn] = System.Convert.DBNull;
            }
            
            public bool IsSECC_TDESCNull() {
                return this.IsNull(this.table_Table.SECC_TDESCColumn);
            }
            
            public void SetSECC_TDESCNull() {
                this[this.table_Table.SECC_TDESCColumn] = System.Convert.DBNull;
            }
            
            public bool Issede_tdescNull() {
                return this.IsNull(this.table_Table.sede_tdescColumn);
            }
            
            public void Setsede_tdescNull() {
                this[this.table_Table.sede_tdescColumn] = System.Convert.DBNull;
            }
            
            public bool Isnum_cuotasNull() {
                return this.IsNull(this.table_Table.num_cuotasColumn);
            }
            
            public void Setnum_cuotasNull() {
                this[this.table_Table.num_cuotasColumn] = System.Convert.DBNull;
            }
            
            public bool Isfecha_inicioNull() {
                return this.IsNull(this.table_Table.fecha_inicioColumn);
            }
            
            public void Setfecha_inicioNull() {
                this[this.table_Table.fecha_inicioColumn] = System.Convert.DBNull;
            }
            
            public bool Isfecha_finNull() {
                return this.IsNull(this.table_Table.fecha_finColumn);
            }
            
            public void Setfecha_finNull() {
                this[this.table_Table.fecha_finColumn] = System.Convert.DBNull;
            }
            
            public bool IsporcentajeNull() {
                return this.IsNull(this.table_Table.porcentajeColumn);
            }
            
            public void SetporcentajeNull() {
                this[this.table_Table.porcentajeColumn] = System.Convert.DBNull;
            }
            
            public bool Ismonto_colacionNull() {
                return this.IsNull(this.table_Table.monto_colacionColumn);
            }
            
            public void Setmonto_colacionNull() {
                this[this.table_Table.monto_colacionColumn] = System.Convert.DBNull;
            }
            
            public bool Isinstitucion_tNull() {
                return this.IsNull(this.table_Table.institucion_tColumn);
            }
            
            public void Setinstitucion_tNull() {
                this[this.table_Table.institucion_tColumn] = System.Convert.DBNull;
            }
            
            public bool IsgradoNull() {
                return this.IsNull(this.table_Table.gradoColumn);
            }
            
            public void SetgradoNull() {
                this[this.table_Table.gradoColumn] = System.Convert.DBNull;
            }
            
            public bool Isinstitucion_gNull() {
                return this.IsNull(this.table_Table.institucion_gColumn);
            }
            
            public void Setinstitucion_gNull() {
                this[this.table_Table.institucion_gColumn] = System.Convert.DBNull;
            }
            
            public bool IshorarioNull() {
                return this.IsNull(this.table_Table.horarioColumn);
            }
            
            public void SethorarioNull() {
                this[this.table_Table.horarioColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRowChangeEvent : EventArgs {
            
            private _TableRow eventRow;
            
            private DataRowAction eventAction;
            
            public _TableRowChangeEvent(_TableRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public _TableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
